version: '3.1'
services:
    yourls:
        build:
            context: ./yourls/
        environment:
            YOURLS_DB_PASS: example
            YOURLS_SITE: 'http://localhost:8082'
            YOURLS_USER: example_user
            YOURLS_PASS: example_pass
            YOURLS_URL_CONVERT: 62
        restart: always
        ports:
            - 8082:80

    mysql:
        build:
            context: ./mysql/
        environment:
            MYSQL_ROOT_PASSWORD: example
        restart: always
