version: '3.6'

services:
    mysql:
        build:
            context: ./mysql/
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
        restart: always

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    yourls:
        build:
            context: ./yourls/
        environment:
            YOURLS_DB_PASS: "${DB_ROOT_PASS}"
            YOURLS_SITE: "${DB_HOSTNAME}"
            YOURLS_USER: "${DB_USER}"
            YOURLS_PASS: "${DB_PASS}"
            YOURLS_URL_CONVERT: 62
            YOURLS_PRIVATE_API: "false"
        restart: always
        ports:
            - 8082:80