FROM bitnami/postgresql:latest
RUN mkdir -p /docker-entrypoint-initdb.d 
RUN mkdir -p /var/lib/apt/lists/partial
RUN apt-get update
RUN apt-get install -y wget
COPY ./postgresql.sql /docker-entrypoint-initdb.d/
