FROM python

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY yourls_api.py .
COPY yourls_client.py .

CMD [ "python", \
    "yourls_client.py", \
    "--addr", "http://simple-yourls_yourls_1", \
    "http://raw.githubusercontent.com/internetofwater/geoconnex.us/master/namespaces/CHyLD/chyld-pilot_ids.csv", \
    "https://raw.githubusercontent.com/internetofwater/geoconnex.us/master/namespaces/SELFIE/SELFIE_ids.csv", \
    "https://raw.githubusercontent.com/internetofwater/geoconnex.us/master/namespaces/ref/states/states.csv", \
    "https://raw.githubusercontent.com/internetofwater/geoconnex.us/master/namespaces/ref/hu02/hu02.csv", \
    "https://raw.githubusercontent.com/internetofwater/geoconnex.us/master/namespaces/ref/hu04/hu04.csv" \
    ]