FROM python

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY yourls_api.py .
COPY populate_db.py .

CMD [ "python", "populate_db.py", "--addr", "http://simple-yourls_yourls_1", "/data/"]