FROM webbben/pygeoapi:test
#pygeoapi last updated 2023-02-16

#add requirements and mods
COPY ./pygeoapi.config.yml /pygeoapi/local.config.yml

# COPY ./schemas.opengis.net /opt/schemas.opengis.net
COPY ./pygeoapi-skin-dashboard /skin-dashboard
