name: Validate all Geoconnex CSVs and bulk XML files

on: [push]

jobs:
  validate-csvs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: uv sync dependencies
        working-directory: ./checks
        run: uv sync --all-extra
      - name: Run prek
        uses: j178/prek-action@v2
